In [1]:
## R version 4.1
library(data.table)

library(openxlsx)

# if (!require("BiocManager", quietly = TRUE))
  #  install.packages("BiocManager")

# BiocManager::install("biomaRt")

library(biomaRt)

In [2]:
setwd("/medpop/esp2/mesbah/projects/Meta_GWAS/MetaGWAS_N900k/pops/")

ch <- fread("CH_pops_gene.preds.txt", header = T, na.strings = "NA")

dnmt <- fread("DNMT3A_pops_gene.preds.txt", header = T, na.strings = "NA")

tet <- fread("TET2_pops_gene.preds.txt", header = T, na.strings = "NA")

head(ch)

head(dnmt)

head(tet)

  ENSGID          PoPS_Score    Y        Y_proj    project_out_covariates_gene
1 ENSG00000186092 -0.0009764183       NA        NA FALSE
2 ENSG00000235249 -0.0176814473       NA        NA FALSE
3 ENSG00000185097  0.0022270281       NA        NA FALSE
4 ENSG00000187634  0.0117274054  0.73140  0.486325  TRUE
5 ENSG00000188976 -0.0848487772 -0.96649 -1.178548  TRUE
6 ENSG00000187961  0.0984214580 -1.20600 -1.384710  TRUE
  feature_selection_gene training_gene GENE
1 FALSE                  FALSE         OR4F5
2 FALSE                  FALSE         OR4F29
3 FALSE                  FALSE         OR4F16
4  TRUE                   TRUE         SAMD11
5  TRUE                   TRUE         NOC2L
6  TRUE                   TRUE         KLHL17

  ENSGID          PoPS_Score  Y        Y_proj      project_out_covariates_gene
1 ENSG00000186092  0.04344102       NA          NA FALSE
2 ENSG00000235249 -0.03264505       NA          NA FALSE
3 ENSG00000185097 -0.04641666       NA          NA FALSE
4 ENSG00000187634 -0.16053095 0.321400  0.08085970  TRUE
5 ENSG00000188976  0.19001353 0.175750 -0.03171365  TRUE
6 ENSG00000187961 -0.28312778 0.016532 -0.16324249  TRUE
  feature_selection_gene training_gene GENE
1 FALSE                  FALSE         OR4F5
2 FALSE                  FALSE         OR4F29
3 FALSE                  FALSE         OR4F16
4  TRUE                   TRUE         SAMD11
5  TRUE                   TRUE         NOC2L
6  TRUE                   TRUE         KLHL17

  ENSGID          PoPS_Score  Y         Y_proj     project_out_covariates_gene
1 ENSG00000186092  0.07773248        NA         NA FALSE
2 ENSG00000235249  0.03795066        NA         NA FALSE
3 ENSG00000185097  0.04404659        NA         NA FALSE
4 ENSG00000187634 -0.14222475 -0.080291 -0.3241051  TRUE
5 ENSG00000188976 -0.18707974 -0.775460 -0.9982861  TRUE
6 ENSG00000187961 -0.18334271 -0.500840 -0.6739443  TRUE
  feature_selection_gene training_gene GENE
1 FALSE                  FALSE         OR4F5
2 FALSE                  FALSE         OR4F29
3 FALSE                  FALSE         OR4F16
4  TRUE                   TRUE         SAMD11
5  TRUE                   TRUE         NOC2L
6  TRUE                   TRUE         KLHL17

In [6]:
# Select the human genes dataset
ensembl <- useEnsembl(biomart = "ensembl", 
                      dataset = "hsapiens_gene_ensembl", 
                      mirror = "useast")

Ensembl site unresponsive, trying www mirror

ERROR: Error in bmRequest(request = request, httr_config = httr_config, verbose = verbose): Gateway Timeout (HTTP 504).

In [5]:
######
# Get the gene intervals
gene_intervals <- getBM(
  attributes = c("ensembl_gene_id", "chromosome_name", "start_position", "end_position"),
  filters = "ensembl_gene_id",
  values = ch$ENSGID,
  mart = ensembl
)

[1] "ch"   "dnmt" "tet"